# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AIAL Lab
email: bakram@ncsu.edu
description: > # this means to ignore newlines until "baseurl:"
  Website of the AI Assisted Learning Lab.
baseurl: /AIAssistedLearningLab
url: https://pages.github.ncsu.edu
domain: pages.github.ncsu.edu

whitelist:
  - jekyll-redirect-from

plugins:
  - jekyll-redirect-from

include:
  - .htaccess
  - _pages

navigation:
  - title: Home
    url: /home/
  - title: Team
    url: /team/
  - title: Publications
    url: /publications/
  # - title: Vacancies
  #   url: /vacancies/
  # - title: Research
  #   url: /research/
  # - title: Pics
  #   url: /pictures/

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
theme: minima
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
