name: Jekyll Site Building
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: [ "self-hosted" ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.1.4'
      - name: Install dependencies
        run: bundle install
      - name: Setup build worktree
        run: git worktree add ${{ runner.temp }}/${{ github.sha }}_site
      - name: Checkout gh-built branch
        run: git -C ${{ runner.temp }}/${{ github.sha }}_site switch gh-built
      - name: Build site for github
        run: bundle exec jekyll build --config _config.yml -d {{ runner.temp }}/${{ github.sha }}_site
      - name: Add all built files
        run: git -C ${{ runner.temp }}/${{ github.sha }}_site add -A
      - name: Commit newly built files
        run: git -C ${{ runner.temp }}/${{ github.sha }}_site commit -m "Update site"
      - name: Push the new changes
        run: git -C ${{ runner.temp }}/${{ github.sha }}_site push 

