name: Jekyll Site Building
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: [ "self-hosted" ]
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout gh-built branch
        uses: actions/checkout@v4
        with:
          ref: gh-built
          path: gh-built
      - name: Change to main folder
        run: cd main
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'
      - name: Install dependencies
        run: bundle install
      - name: Build site for github
        run: bundle exec jekyll build --config _config.yml -d ../site
      - name: Add all built files
        run: git -C ../site add -A
      - name: Commit newly built files
        run: git -C ../site commit -m "Update site"
      - name: Push the new changes
        run: git -C ../site push 

