name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install

      - name: Build the site
        run: bundle exec jekyll build --config _config.yml,_vhost_config.yml -d _site

      - name: Push built site to built branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: built

