  GNU nano 8.5           .github/workflows/jekyll-build.yml           Modified

name: Build and Deploy Jekyll Site to `built` Branch

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Bundler and dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build --config _config.yml,_vhost_config.yml -d _site

      - name: Deploy to `built` branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_branch: built
          publish_dir: _site
          github_token: ${{ secrets.GITHUB_TOKEN }}
