name: Production build
on:
  push:
    branches:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      config: '_config.yml,_vhost_config.yml'
      branch: 'built'
