name: Production build
on:
  push:
    branches:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      config: '_config.yml,_vhost_config.yml'
      branch: 'built'